#Makefile at top of application tree
TOP = .
include $(TOP)/configure/CONFIG

DIRS += configure ethercatmcApp
ethercatmcApp_DEPEND_DIRS   = configure

DIRS += ethercatmcExApp
ethercatmcExAppExApp_DEPEND_DIRS = configure ethercatmcApp

include $(TOP)/configure/RULES_TOP


